### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by xiawanyingtest** [foxiswho/k8s-nacos-sentinel-rocketmq-zipkin-elasticsearch-redis-mysql#1]
能提供下mysql的k8s脚本吗？
还有这句
服务器IP 说明
如果更改了服务器IP 为其他IP，那么请全局全部替换成你改的IP
是什么意思

**Comment by foxiswho** [comment]
你改的IP是   宿主机IP

到 mariadb 目录下，更改 pod.yml  把 mariadb 容器镜像 改成 mysql 镜像 就是你需要的  mysql .
